### ISSUE TITLE
If you switch out and enemy responds with Rollout, the game claims Rollout has no PP left

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/polishedcrystal#78]

**Comment by roukaour** [comment]
Probably related:

"I was fighting a wild Ditto and he transformed into my Geodude. Before he attacks the message "But no PP is left for the move!" or "But Ditto has no PP left for (move name)!" appears. I've seen this happen when Ditto uses Rollout, AncientPower and Magnitude; but not when it uses Tackle. In trainer battles the message starts appearing when Ditto uses one of the moves I mentioned for the second time. Also that message appears only when my active Pokémon is Geodude, so I think that the bug is related to Sturdy."

**Comment by FredrIQ** [comment]
Can't reproduce, asked for more info in the PC thread.

**Comment by FredrIQ** [comment]
This was actually fixed as part of 66a290a3ef7e3ba3d5a5470949707f13ad0f9422 which also seems to have been what messed with the PP values.
